 
SAMPLES = [
    "NA19625",
    "NA19700",
    "NA19701",
    "NA19703",
    "NA19704",
    "NA19707",
    "NA19711",
    "NA19712",
    "NA19713",
    "NA19818",
    "NA19819",
    "NA19834",
    "NA19835",
    "NA19900",
    "NA19901",
    "NA19904",
    "NA19908",
    "NA19909",
    "NA19913",
    "NA19914",
    "NA19916",
    "NA19917",
    "NA19920",
    "NA19921",
    "NA19922",
    "NA19923",
    "NA19982",
    "NA19984",
    "NA20126",
    "NA20127",
    "NA20274",
    "NA20276",
    "NA20278",
    "NA20281",
    "NA20282",
    "NA20287",
    "NA20289",
    "NA20291",
    "NA20294",
    "NA20296",
    "NA20298",
    "NA20299",
    "NA20314",
    "NA20317",
    "NA20318",
    "NA20320",
    "NA20321",
    "NA20332",
    "NA20334",
    "NA20339",
    "NA20340",
    "NA20342",
    "NA20346",
    "NA20348",
    "NA20351",
    "NA20355",
    "NA20356",
    "NA20357",
    "NA20359",
    "NA20362",
    "NA20412"
        ]

import pandas as pd

# ---------------------------------------------------------
# Load population info
# ---------------------------------------------------------
POP_INFO_FILE = '../250320-1tgp/data/popinfo.txt'
POP_INFO = pd.read_csv(POP_INFO_FILE, sep='\t', names=['Sample', 'POP', 'REG', 'Sex'])

# List of male samples
MALE_SAMPLES = set(POP_INFO.query("Sex == 'male'").Sample.tolist())

def is_male(wildcards):
    """Return True/False depending on whether sample is male"""
    return wildcards.sample in MALE_SAMPLES


rule all:
    input:
        expand('data/{sample}_0.bed', sample=SAMPLES),
        expand('data/{sample}_1.bed', sample=SAMPLES),

# ---------------------------------------------------------
# Rule
# ---------------------------------------------------------
rule remove_X_when_male:
    input:
        bed_0 = '../251002-smooth-tracts/data/corrected_phase_island/{sample}_0.bed',
        bed_1 = '../251002-smooth-tracts/data/corrected_phase_island/{sample}_1.bed',
    output:
        bed_0 = 'data/{sample}_0.bed',
        bed_1 = 'data/{sample}_1.bed',
    params:
        male = is_male
    shell:
        r"""
        if [ "{params.male}" = "True" ]; then
            # Remove chrX for males
            grep -v 'chrX' {input.bed_0} > {output.bed_0}
        else
            # Copy as is for females
            cp {input.bed_0} {output.bed_0}
        fi

        # Copy haplotype 1 unchanged
        cp {input.bed_1} {output.bed_1}
        """

